### ISSUE TITLE
Accessing source data

### ISSUE THREAD

**Issue by PauBadiaM** [IGVF-DACC/igvf-catalog#9]
Hi,

As far as I understood, right now this API builds the knowledge graph only with the sample data stored in `data/samples/`. May I ask how did you generate them? For example for the eQTL data, how could I access the total amount of available data? Thanks!

**Comment by hitz** [comment]
the eQTL data we are importing was downloaded from GTEx.  Other data produced by the IGVF project (and other public xQTL datasets would be added later as well.   

https://storage.googleapis.com/gtex_analysis_v8/single_tissue_qtl_data/GTEx_Analysis_v8_eQTL.tar
